moveo6:
  controller:
    state:
      type: joint_state_controller/joint_state_controller
      publish_rate: 50
    position:
      moveo6_arm:
        type: position_controllers/JointPositionController
        joint: [ joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
